### PR TITLE
fixed artist page link && strapi data

### PR DESCRIPTION
**Pull request by zahirekrem09**
#146 #147

### CODE REVIEW

**Review by 7alip — CHANGES_REQUESTED** [review]
Thank you! Links seem to be working correct. The only thing I've noticed is:

https://github.com/wsvvrijheid/wsvvrijheid/blob/66faeca1b628429c3520a44f3b35e64385befefa/src/pages/club/artist/%5Busername%5D.js#L24

```jsx
 <Layout seo={{ title }} isDark> 
```

we can add `isDark` prop to Layout as we use Hero component in this page. Otherwise link colors will look a bit ugly.

**Comment by MustafaTRKYLMZ** [comment]
I saw this error which is "alternative text" in the page. Maybe we can fix it.   
image

If it is possible we can make hover on the user avatar. It might be looks good.

**Comment by zahirekrem09** [comment]
> 

I did not understand exactly what to do.

**Comment by 7alip** [comment]
> I saw this error which is "alternative text" in the page.

I think it's because of the image format (auth-profile-bg.avif). We need to change it with jpeg or png format. Let's do it later.

**Comment by 7alip** [comment]
> I did not understand exactly what to do.

He meant that: We can wrap Avatar + username  together with link. So,  cursor will be pointer when you hover on the avatar as well.

**Comment by 7alip** [comment]
- [ ] Wrap avatar and username with Navigate component
- [ ] Add `isDark` to page Layout

**Review by 7alip — APPROVED** [review]
Thank you

**Pull request merged**
