### PR TITLE
Art like and view

### PR DESCRIPTION
**Pull request by 7alip**

### CODE REVIEW

**Comment by 7alip** [comment]
Removed liked_arts, liked_blogs information from user data. Because session data shouldn't be large. We can later decide about which data will be included in session.

**Comment by 7alip** [comment]
Hi @MustafaTRKYLMZ 

Can you also test that:

- [ ] 1. Try like in club page. Check localstorage
- [ ] 2. Try undo like in club page. Check localstorage
- [ ] Keep some arts as liked by public user. (localstorage should't be empty)
- [ ] Login and check. Auth user likes and public user likes should be different in the same pc
- [ ] Test step 1 and  step 2 for auth user

**Comment by MustafaTRKYLMZ** [comment]
> Hi @MustafaTRKYLMZ
> 
> Can you also test that:
> 
> * [x]  1. Try like in club page. Check localstorage
> * [x]  2. Try undo like in club page. Check localstorage
> * [x]  3. Try like in single art page. Check localstorage
> * [ ]  4. Try undo like in single art page. Check localstorage
> * [ ]  Keep some arts as liked by public user. (localstorage should't be empty)
> * [ ]  Login and check. Auth user likes and public user likes should be different in the same pc
> * [ ]  Test step 1, 2, 3 and 4 for auth user

When I log in single page doesn't working (Link doesn't working). That is why I couldn't tested  like in the single page 

`Application error: a client-side exception has occurred (see the browser console for more information).`

**Review by MustafaTRKYLMZ — APPROVED** [review]
looks perfect

**Pull request merged**
